Repository UpLazrD/space-station-14, pull requests merged in 2024-12, with the labels that each got.

#1 Лобби
  Content.Client/GameTicking/Managers/ClientGameTicker.cs
  Content.Client/Lobby/LobbyState.cs
  Content.Client/Lobby/UI/LobbyGui.xaml
  Content.Client/Lobby/UI/LobbyGui.xaml.cs
  Content.Client/Options/UI/Tabs/MiscTab.xaml
  Content.Client/Options/UI/Tabs/MiscTab.xaml.cs
  Content.Client/Stylesheets/StyleNano.cs
  Content.Server/GameTicking/GameTicker.Lobby.cs
  Content.Server/GameTicking/GameTicker.LobbyBackground.cs
  Content.Server/GameTicking/GameTicker.RoundFlow.cs
  Content.Shared/GameTicking/SharedGameTicker.cs
  Content.Shared/_DW/CCvars/CCvars.cs
  Resources/Locale/ru-RU/escape-menu/ui/options-menu.ftl
  Resources/Prototypes/_DW/Guidebook/rules.yml
  Resources/Textures/Interface/Nano/nanoheading.svg.96dpi.png
Labels: Changes: UI, Changes: Localization, S: Untriaged, size/L

#2 Maps lower player limit remove
  Resources/Prototypes/Corvax/Maps/avrite.yml
  Resources/Prototypes/Corvax/Maps/delta.yml
  Resources/Prototypes/Corvax/Maps/gelta.yml
  Resources/Prototypes/Corvax/Maps/ishimura.yml
  Resources/Prototypes/Corvax/Maps/outpost.yml
  Resources/Prototypes/Corvax/Maps/pilgrim.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/Maps/bagel.yml
  Resources/Prototypes/Maps/box.yml
  Resources/Prototypes/Maps/fland.yml
  Resources/Prototypes/Maps/marathon.yml
  Resources/Prototypes/Maps/meta.yml
  Resources/Prototypes/Maps/train.yml
Labels: S: Untriaged, Changes: Map, Changes: No C#

#3 утильский протокол "ГОЙДА"
  Resources/Prototypes/_DW/Entities/Objects/Weapons/Guns/mining.yml
  Resources/Prototypes/_DW/Entities/Objects/Weapons/Melee/meme.yml
  Resources/Prototypes/_DW/Entities/Objects/Weapons/Melee/mining.yml
  Resources/Prototypes/_DW/Entities/Objects/Weapons/Projectiles/Projectile.yml
  Resources/Textures/_DW/Objects/Weapons/Crusher.rsi/meta.json
  Resources/Textures/_DW/Objects/Weapons/Crusher.rsi/v2.png
  Resources/Textures/_DW/Objects/Weapons/Crusher.rsi/v3.png
  Resources/Textures/_DW/Objects/Weapons/Snipingacelerator.rsi/icon.png
  Resources/Textures/_DW/Objects/Weapons/Snipingacelerator.rsi/meta.json
  Resources/Textures/_DW/Objects/Weapons/Toolboxonastick.rsi/icon.png
  Resources/Textures/_DW/Objects/Weapons/Toolboxonastick.rsi/meta.json
Labels: Changes: Localization, S: Untriaged, size/L, Changes: No C#, Changes: Sprites
